version: '3.8'
services:
    postgres:
        image: postgres
        restart: always
        environment:
          - POSTGRES_USER=christian
          - POSTGRES_PASSWORD=index
          - DATABASE_HOST=127.0.0.1
          - POSTGRES_DB=core
        ports:
          - '5438:5432'