GET http://127.0.0.1:8080/user

### New user
POST http://127.0.0.1:8080/user/create
Content-Type: application/json

{
    "id": 4,
    "usuario": "Carlos",
    "mensaje": "Esto es una prueba",
    "fecha": "2020-01-01"
}